insert into CHALLENGE.TB_BRANCHS (BRANCH_ID, BRANCH_NAME, BRANCH_CITY, BRANCH_STATE, USER_CODE)
values (1500, 'AG. PAULISTA', 'SÃO PAULO', 'SP', 'admin');

insert into CHALLENGE.TB_BRANCHS (BRANCH_ID, BRANCH_NAME, BRANCH_CITY, BRANCH_STATE, USER_CODE)
values (1501, 'AG. GRANJA VIANNA', 'SÃO PAULO', 'SP', 'admin');

insert into CHALLENGE.TB_BRANCHS (BRANCH_ID, BRANCH_NAME, BRANCH_CITY, BRANCH_STATE, USER_CODE)
values (1502, 'AG. STO MARO', 'SÃO PAULO', 'SP', 'admin');
commit;